---
- name: Receive arguments from job template
  hosts: all
  gather_facts: false

  tasks:
    - name: Print arguments
      debug:
        msg: "param: {{ parameters }}, Platform: {{ parameters.Platform }}"